/**
 * Auto-generated by scripts/build-knowledge-hub-extras.mjs from resources/*.md
 * Do not hand-edit — re-run the script after adding markdown sources.
 */

export const KNOWLEDGE_HUB_EXTRA_TOOLS = [
  {
    id: "ai-and-creative-arts",
    name: { en: "Lesson set: how AI tools intersect with making art and music—and what to question", ar: "مجموعة دروس: أدوات الذكاء الاصطناعي والفن والموسيقى — وماذا نسأل" },
    category: "creation",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Addresses bias in representation and identity through self-portraits, comparing how students see themselves versus how AI represents them.",
      ar: "يربط بين الإبداع والآلات الذكية والأسئلة الأخلاقية حول المؤلف والأصالة."
    },
    link: "https://dayofai.org/units/ai-and-the-creative-arts",
    tags: ["lesson_plan","activity","ethics"]
  },
  {
    id: "ai-and-elections",
    name: { en: "Lesson set: deepfakes, campaigns, and why automated media matters for democracy", ar: "دروس حول التزييف العميق والحملات ولماذا يهم الإعلام الآلي للديمقراطية" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Analyzes how AI influences democratic processes through deepfakes, predictive analytics, and campaign messaging. Perfect for discussing the ethical risks of misinformation and the need for responsible AI policies in society.",
      ar: "قضايا موجهة للنقاش حول الثقة والمعلومات أثناء الانتخابات."
    },
    link: "https://dayofai.org/units/ai-and-elections",
    tags: ["lesson_plan","activity","ethics"]
  },
  {
    id: "ai-booklist",
    name: { en: "Books to read together about AI, ethics, and growing up with tech", ar: "كتب للقراءة معاً عن الذكاء الاصطناعي والأخلاقيات والنمو مع التقنية" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Curated selection of books to introduce AI concepts through storytelling across all grade levels from early childhood to late adolescence.",
      ar: "قائمة مقترحة لمناقشة الذكاء الاصطناعي والقيم الرقمية مع الأطفال والمراهقين في أجواء عائلية."
    },
    link: "https://dayofai.org/units/ai-booklist",
    tags: ["resource_list","reading_guide","bibliography"]
  },
  {
    id: "ai-ethics-debate",
    name: { en: "Structured debate prompts on fairness, bias, responsibility, and rules for AI", ar: "مطالبات مناظرة منظمة حول العدالة والتحيز والمسؤولية وقواعد الذكاء الاصطناعي" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Uses a structured debate to explore real-world dilemmas like facial recognition in schools and data privacy. It forces students to think as different stakeholders (tech companies, governments, users), fostering empathy and complex ethical reasoning.",
      ar: "إطار للحوار الصفي حول القيم عند استخدام أنظمة آلية."
    },
    link: "https://dayofai.org/units/ai-ethics-debate",
    tags: ["lesson_plan","activity","debate"]
  },
  {
    id: "ai-fairness-responsibly-sports",
    name: { en: "Case-based lesson on fairness when AI scores, ranks, or officiates in sports", ar: "درس بالحالات: العدالة عندما يقيّم الذكاء الاصطناعي الأداء في الرياضة" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Analyzes how AI makes decisions in sports (officiating, injuries, coaching) and where human judgment must remain central. Perfect for discussing fairness and bias in a high-interest context.",
      ar: "يستكشف سوء التصنيف والتحيز في الأنظمة التحكيمية أو الإحصائية."
    },
    link: "https://dayofai.org/units/changing-the-game-using-ai-fairly-and-responsibly-in-sports",
    tags: ["lesson_plan","activity","ethics"]
  },
  {
    id: "ai-foundations-high-school",
    name: { en: "High-school depth on systems, data, limits, and ethics", ar: "عمق لمرحلة الثانوية: الأنظمة والبيانات والحدود والأخلاقيات" },
    category: "learning",
    ageMin: 14,
    ageMax: 18,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Provides the technical bridge between how AI works (neural networks) and its social impact. Essential for teaching high schoolers that algorithmic bias isn't just a mistake, but a result of how data and algorithms are structured.",
      ar: "يتدرج نحو أسئلة سياسية وتقنية تناسب الطلاب الأكبر سناً."
    },
    link: "https://dayofai.org/units/ai-foundations-for-high-school",
    tags: ["lesson_plan","foundational","unit"]
  },
  {
    id: "ai-foundations-k2",
    name: { en: "Early-elementary introduction to patterns, data, and “smart” machines", ar: "مقدمة للمرحلة الابتدائية المبكرة: الأنماط والبيانات والآلات الذكية" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Foundational unit for the youngest students to understand the difference between human and machine intelligence.",
      ar: "مفاهيم بسيطة وتمثيلات ملموسة لبناء الحدس قبل الصفوف العليا."
    },
    link: "https://dayofai.org/units/ai-foundations-grades-k-2-ages-5-7",
    tags: ["curriculum","lesson_plan","foundational"]
  },
  {
    id: "ai-foundations-middle-grades",
    name: { en: "Middle-grades overview of how AI works with everyday examples", ar: "نظرة عامة لمرحلة المتوسط: كيف يعمل الذكاء الاصطناعي بأمثلة يومية" },
    category: "learning",
    ageMin: 10,
    ageMax: 15,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Provides a deep dive into how AI systems perceive and reason. Essential for Ethika to explain that AI doesn't 'think' like a human, but processes data through specific logic gates, which is where bias can be introduced.",
      ar: "يربط بين الحياة الواقعية والخوارزميات والبيانات بلغة واضحة."
    },
    link: "https://dayofai.org/units/ai-foundations-for-middle-grades",
    tags: ["lesson_plan","foundational","unit"]
  },
  {
    id: "ai-literacy-15-min",
    name: { en: "Quick primer for teens and adults: what AI is and where it shows up", ar: "مقدمة قصيرة للمراهقين والكبار: ما الذكاء الاصطناعي وأين يظهر في حياتنا؟" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Quick, flexible activities to build curiosity and responsible digital citizenship without requiring extensive prep time.",
      ar: "جلسة قصيرة تشرح المفاهيم الأساسية دون مصطلحات معقدة، مناسبة للبيت أو الفصل."
    },
    link: "https://dayofai.org/units/ai-literacy-in-15-minutes-or-less",
    tags: ["lesson_plan","warm_up","activity"]
  },
  {
    id: "ai-literacy-family-playlist",
    name: { en: "Short videos for families on core AI ideas and dinner-table prompts", ar: "مقاطع فيديو قصيرة للعائلات حول مفاهيم الذكاء الاصطناعي الأساسية" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "A curated video series that explains AI concepts in simple terms for families. It covers everything from what AI is to how it impacts daily life, providing a visual and accessible way to introduce AI ethics at home.",
      ar: "قائمة تشغيل لمراجعة سريعة مع الأطفال وطرح أسئلة على مائدة الطعام."
    },
    link: "https://www.youtube.com/playlist?list=PL8TjVyuBdsCnGPGStOLyW88w7cRPU_cql",
    tags: ["video_playlist","educational_media","toolkit"]
  },
  {
    id: "ai-literacy-toolkit-families-presentation",
    name: { en: "Slides and talking points for a parent or community night on AI literacy", ar: "عرض تقديمي وحديث موجه لأولياء الأمور أو مجتمع المدرسة حول محو أمية الذكاء الاصطناعي" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "This presentation defines AI literacy as the ability to understand how AI works and to think critically about its ethical and societal consequences. It provides practical tools for families to discuss AI's presence in daily life, its benefits, and its risks, such as bias and misinformation.",
      ar: "شرائح ونقاط للنقاش في أمسية للآباء حول التوقعات والأمان والاستخدام المسؤول."
    },
    link: "https://docs.google.com/presentation/d/1f-21spAtkCg60Y8-oV3D6tbSNEPi6mVVWvP7nVLVlxk/edit",
    tags: ["presentation","toolkit","instructional_resource"]
  },
  {
    id: "ai-literacy-toolkit-implementation-guide",
    name: { en: "Step-by-step manual for rolling out AI literacy across grades or a district", ar: "دليل تنفيذ خطوة بخطوة لنشر محو أمية الذكاء الاصطناعي بين الصفوف أو على مستوى المنطقة" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Curated AI or digital citizenship resource you can use with guidance at home or in school.",
      ar: "إرشادات عملية للإدارة والمعلمين لدمج الدروس والتقييم بسلاسة."
    },
    link: "https://drive.google.com/file/d/1fbM9-rrHOPRGLnB4XnGTQNn_3yLXpNHs/view",
    tags: ["implementation_guide","facilitator_guide","toolkit"]
  },
  {
    id: "ai-literacy-toolkit-start-here",
    name: { en: "Orientation for schools and families starting a structured AI literacy effort", ar: "نقطة البداية لبرنامج محو أمية الذكاء الاصطناعي المنظم في المدرسة أو البيت" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Provides the logistical framework to bring AI literacy from the classroom to the home. It ensures that ethical AI discussions involve families through curated videos, conversation cards, and reflection activities.",
      ar: "ملف توجيهي لمن يبدأ أول مرة في تصميم مسار تعلّم حول الذكاء الاصطناعي."
    },
    link: "https://docs.google.com/document/d/1Q0u-alSnNM8E48VVB-L1NVwJBu-2jEamskQEV8mcXzc/edit",
    tags: ["implementation_guide","toolkit","instructional_resource"]
  },
  {
    id: "ai-surveillance-human-responsibility",
    name: { en: "Discussion materials on surveillance, profiling, and human rights in an AI-mediated world", ar: "مواد نقاش حول المراقبة والملفات الرقمية وحقوق الإنسان في عالم يحكمه الذكاء الاصطناعي" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Directly addresses AI surveillance and the critical difference between AI predictions and human decisions. Includes a simulator to explore bias and privacy, perfect for discussing human responsibility.",
      ar: "يربط بين الخصوصية والعدالة عند اتخاذ القرار آلياً."
    },
    link: "https://dayofai.org/units/from-data-to-decision-ai-surveillance-and-human-responsibility",
    tags: ["lesson_plan","activity","simulation"]
  },
  {
    id: "ai-vocabulary-cards",
    name: { en: "Printable cards for teaching core AI vocabulary in class", ar: "بطاقات مفردات قابلة للطباعة لمفاهيم الذكاء الاصطناعي الأساسية" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Printable or digital cards used as warm-ups or 5-15 minute lessons to reinforce key AI vocabulary with real-world examples.",
      ar: "يدعم بناء لغة مشتركة بين المعلم والطالب حول النماذج والبيانات."
    },
    link: "https://dayofai.org/units/vocabulary-cards",
    tags: ["resource_list","glossary","educational_tool"]
  },
  {
    id: "boost-digital-literacy-wellbeing-families",
    name: { en: "Ideas and routines to strengthen digital habits and wellbeing at home", ar: "أفكار وروتينات لتعزيز العادات الرقمية والرفاهية في البيت" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Directly addresses the common 'How do I start?' question from families. It provides curated, actionable activities that promote healthy tech habits, critical thinking, and emotional well-being in digital spaces.",
      ar: "مقال وأنشطة مقترحة لموازنة الشاشات والنوم والتركيز العاطفي للعائلة."
    },
    link: "https://www.commonsense.org/education/articles/when-families-ask-about-activities-to-boost-digital-literacy-well-being",
    tags: ["article","family_resource","instructional_resource"]
  },
  {
    id: "can-machines-be-creative",
    name: { en: "Philosophy-of-AI lesson: creativity, imitation, and authorship", ar: "درس فلسفي: هل يمكن للآلات أن تبدع، أم تقلّد فقط؟" },
    category: "creation",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Explores the intersection of AI and art, questioning what it means to be 'creative' and who owns AI-generated content.",
      ar: "مناقشة الصدق الفني والإنسان في ظل التوليد الآلي."
    },
    link: "https://dayofai.org/units/can-machines-be-creative",
    tags: ["lesson_plan","activity","ethics"]
  },
  {
    id: "common-sense-digital-connections-hub",
    name: { en: "One place to browse Common Sense “Digital Connections” lessons and downloads", ar: "بوابة واحدة لتصفح دروس «الاتصال الرقمي» من كومن سينس وتحميل المواد" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Provides the pedagogical framework for the Digital Connections interactive series. It offers teachers ready-to-use lesson plans that bridge the interactive experience with classroom discussion, ensuring that digital citizenship concepts are deeply integrated into student learning.",
      ar: "فهرس يوجّه المعلمين والآباء إلى الدروس والأنشطة والموارد القابلة للتنزيل."
    },
    link: "https://www.commonsense.org/education/digital-connections",
    tags: ["educator_hub","lesson_plans","digital_citizenship"]
  },
  {
    id: "digital-connections-interactive-series-middle-school",
    name: { en: "Middle-school digital life lessons you can teach from the browser (Common Sense)", ar: "دروس الحياة الرقمية لمرحلة المتوسط من المتصفح (كومن سينس)" },
    category: "learning",
    ageMin: 10,
    ageMax: 15,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Provides an immersive and interactive way for middle schoolers to practice digital citizenship. By following the characters Daveed and Skylar, students make real-time decisions about technology use, fostering empathy, critical thinking, and responsible online behavior.",
      ar: "سلسلة تفاعلية تغطي الصداقات، الخصوصية، والمواطنة الرقمية بلغة مناسبة للمراهقين."
    },
    link: "https://www.digitalconnections.org/",
    tags: ["interactive_video_series","curriculum","digital_citizenship"]
  },
  {
    id: "digital-connections-video-series-playlist",
    name: { en: "Video series on friendships, media, and online choices for middle schoolers", ar: "سلسلة فيديو عن الصداقات والإعلام والخيارات الرقمية لطلاب المتوسط" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "A foundational video collection designed to accompany the official Common Sense Digital Citizenship Curriculum. Uses relatable storytelling (Daveed and Skylar) to address critical digital citizenship topics for middle schoolers. Covers ethical issues such as the 24/7 news cycle, digital footprints, and online relations",
      ar: "فيديوهات قصيرة تدعم النقاش العائلي حول السلوك الآمن عبر الإنترنت."
    },
    link: "https://www.youtube.com/playlist?list=PLxc-QYpD02mbJnlq1v46vr-ldYeeZKmPm",
    tags: ["video_playlist","digital_citizenship","curriculum_support","instructional_resource"]
  },
  {
    id: "ecobits-explorers-microbits",
    name: { en: "Outdoor and classroom sensing projects with micro:bit (environment and data)", ar: "مشاريع استشعار داخل وخارج الفصل باستخدام micro:bit (البيئة والبيانات)" },
    category: "coding",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Teaches students how to collect and interpret real-world data responsibly. It emphasizes the importance of data integrity and how local data collection can inform global climate action.",
      ar: "أنشطة عملية تربط بين البيئة وجمع البيانات والتبرمج للمتعلمين الصغار."
    },
    link: "https://dayofai.org/units/ecobits-explorers-environmental-data-collection-and-analysis-using-microbits",
    tags: ["lesson_plan","activity","data_science"]
  },
  {
    id: "ethical-use-of-ai-exploration",
    name: { en: "Activities for exploring responsible use of AI tools in learning", ar: "أنشطة لاستكشاف الاستخدام المسؤول لأدوات الذكاء الاصطناعي في التعلم" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Critical unit for establishing classroom or institutional norms. It moves from theory to practice by having students create their own 'Ethical AI Guidelines', focusing on responsibility and transparency.",
      ar: "تمارين على الشفافية والاستشهاد بالمصادر عند استخدام المساعدات الآلية."
    },
    link: "https://dayofai.org/units/ethical-use-of-ai-exploration",
    tags: ["lesson_plan","activity","ethics"]
  },
  {
    id: "generative-ai-mit-app-inventor",
    name: { en: "Build a simple mobile app that calls a generative model (MIT App Inventor walkthrough)", ar: "بناء تطبيق بسيط يستدعي نموذجاً توليدياً عبر MIT App Inventor" },
    category: "coding",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Students transition from AI consumers to AI creators. By building apps with ChatGPT and DALL-E, they encounter real-world challenges in prompt engineering, bias in generated content, and responsible API usage.",
      ar: "نشاط برمجي بالكتل يربط بين تطبيق الهاتف والذكاء الاصطناعي التوليدي خطوة بخطوة."
    },
    link: "https://dayofai.org/units/generative-ai-with-mit-app-inventor",
    tags: ["lesson_plan","activity","coding"]
  },
  {
    id: "google-generative-ai-for-educators",
    name: { en: "Practical classroom guide to Chat-style AI: tasks, limits, and academic integrity", ar: "دليل عملي للمعلمين حول أدوات الدردشة التوليدية: مهام، حدود، والنزاهة الأكاديمية" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Professional development resource for teachers to master Generative AI tools (Gemini, NotebookLM). It focuses on efficiency, creative lesson enhancement, and responsible AI usage in the classroom, enabling teachers to lead AI adoption ethically.",
      ar: "يساعد المعلمين على دمج أدوات مثل ChatGPT في التدريس مع ضوابط واضحة."
    },
    link: "https://grow.google/ai-for-educators/",
    tags: ["professional_development","course","teacher_training"]
  },
  {
    id: "how-are-we-quantified-by-ai",
    name: { en: "Lesson on how data and models infer traits, scores, and risk labels", ar: "درس حول كيف تستنتج البيانات والنماذج الصفات والدرجات ومؤشرات المخاطر" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Explores the ethical implications of turning human traits into data. It helps students understand how AI classification can lead to exclusion or discrimination, focusing on the social impact of quantification.",
      ar: "يفتح الحوار حول الملفات الرقمية والتمييز غير العادل."
    },
    link: "https://dayofai.org/units/how-are-we-quantified-by-ai",
    tags: ["lesson_plan","activity","data_ethics"]
  },
  {
    id: "how-do-machines-create",
    name: { en: "Explainer on how generative models produce images, audio, and text", ar: "شرح مبسط لكيفية توليد النماذج للصور والصوت والنص" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Explains the technical difference between predictive and generative AI. It focuses on the societal and ethical impacts of deepfakes, helping students develop critical media literacy skills.",
      ar: "يعرض خطوات التدريب والتوليد دون معادلات معقدة."
    },
    link: "https://dayofai.org/units/how-do-machines-create",
    tags: ["lesson_plan","activity","ethics"]
  },
  {
    id: "how-do-machines-learn-lesson",
    name: { en: "Concept lesson on training data, patterns, and generalization", ar: "مفهوم تعلم الآلة: بيانات التدريب والأنماط والتعميم" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Explains the concept of supervised learning and how machines use data to recognize patterns and make predictions.",
      ar: "أساس لفهم أخطاء النموذج والتحيز في البيانات."
    },
    link: "https://dayofai.org/units/how-do-machines-learn",
    tags: ["lesson_plan","activity","interactive"]
  },
  {
    id: "how-machines-learn-coding",
    name: { en: "Hands-on coding activity: train a small model and inspect results", ar: "نشاط برمجي: تدريب نموذج صغير ومراقبة النتائج" },
    category: "coding",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Teaches the technical side of AI through block-based coding (Scratch), helping students build their own simple learning models.",
      ar: "تجربة عملية لربط الكود بسلوك النموذج."
    },
    link: "https://dayofai.org/units/how-do-machines-learn-with-coding",
    tags: ["curriculum","activity","coding"]
  },
  {
    id: "how-we-teach-machines",
    name: { en: "Intro to labels, datasets, and teaching systems from examples", ar: "مقدمة في التسميات ومجموعات البيانات وتعليم الأنظمة من الأمثلة" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Introduces foundational AI concepts (data, patterns, algorithms) for young learners through unplugged, device-free activities.",
      ar: "يشرح دور الإنسان في «تغذية» التعلم الآلي."
    },
    link: "https://dayofai.org/units/how-we-teach-machines",
    tags: ["lesson_plan","activity","hands_on"]
  },
  {
    id: "human-rights-and-ai",
    name: { en: "Human-rights framing for automated decisions, bias, and accountability", ar: "إطار حقوق الإنسان للقرارات الآلية والتحيز والمساءلة" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Directly aligns with Ethika's mission by connecting AI ethics to fundamental human rights. It uses UNESCO principles to evaluate AI impacts on privacy, safety, and equality, culminating in a student-led advocacy project.",
      ar: "يربط بين المعايير الدولية وتجربة الأفراد مع الأنظمة الذكية."
    },
    link: "https://dayofai.org/units/human-rights-and-artificial-intelligence",
    tags: ["lesson_plan","activity","project"]
  },
  {
    id: "impact-ai-environment",
    name: { en: "How large AI systems use energy and materials—and what to discuss with students", ar: "أثر أنظمة الذكاء الاصطناعي الكبيرة على الطاقة والموارد — وماذا نناقش مع الطلاب" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Explores the dual nature of AI in environmental contexts: its role in climate solutions versus its massive energy consumption and e-waste production. Crucial for a holistic ethical perspective on technology.",
      ar: "قضايا بيئية وأخلاقية حول تدريب النماذج واستخدامها."
    },
    link: "https://dayofai.org/units/the-impact-of-ai-on-the-environment",
    tags: ["lesson_plan","activity","ethics"]
  },
  {
    id: "making-sense-of-surroundings",
    name: { en: "Data and sensors: noticing patterns in the environment around you", ar: "البيانات وأجهزة الاستشعار: ملاحظة الأنماط في البيئة من حولنا" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Introduces foundational data literacy by connecting sensory observations to global climate patterns. It teaches students how data is collected, organized, and interpreted, which is the first step in understanding algorithmic bias.",
      ar: "أنشطة تربط بين القياس والاستنتاج والفضول العلمي."
    },
    link: "https://dayofai.org/units/making-sense-of-our-surroundings",
    tags: ["lesson_plan","activity","data_literacy"]
  },
  {
    id: "planning-guide-2025",
    name: { en: "Year-long AI literacy planning workbook: themes, pacing, and classroom-ready blocks", ar: "دفتر تخطيط سنوي لمحو أمية الذكاء الاصطناعي: محاور، وتيرة، ووحدات جاهزة للصف" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Comprehensive workbook for planning AI literacy integration, including family communication templates and implementation checklists.",
      ar: "يتضمن خطة طويلة المدى لربط دروس الذكاء الاصطناعي عبر العام الدراسي بما يناسب المعلمين والمنسقين."
    },
    link: "https://dayofai.org/planning-guide",
    tags: ["planning_guide","workbook","educational_resource"]
  },
  {
    id: "telling-climate-stories-data",
    name: { en: "Using evidence and charts to tell accurate climate stories (data literacy)", ar: "استخدام الأدلة والرسوم البيانية لسرد قصص مناخية دقيقة (محو أمية البيانات)" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Teaches students how to humanize raw data. It moves beyond technical analysis to ethical communication, showing how data can be used to tell compelling, evidence-based stories about climate impact.",
      ar: "يمكن العائلات من التحقق من المعلومات البيئية عبر المصادر."
    },
    link: "https://dayofai.org/units/telling-climate-stories-with-data",
    tags: ["lesson_plan","project","data_science"]
  },
  {
    id: "the-brain-behind-the-bot",
    name: { en: "Analogies between brains and neural networks—without oversimplifying wrong", ar: "تشابهات بين الدماغ والشبكات العصبية — مع تجنب التبسيط الخاطئ" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Perfect for introducing the youngest students to AI by comparing how their own brains learn versus how a robot 'brain' learns, establishing a foundation for human-centric AI understanding.",
      ar: "يساعد على فهم حدود المقارنة بين الإنسان والآلة."
    },
    link: "https://dayofai.org/units/thebrainbehindthebot",
    tags: ["lesson_plan","activity","introductory"]
  },
  {
    id: "the-cognitive-card-game",
    name: { en: "Card prompts for comparing human cognition with machine learning ideas", ar: "لعب بطاقات لمقارنة الإدراك البشري وأفكار تعلم الآلة" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Introduces the concept of 'Cognitive Debt' versus 'Effort'. It helps students distinguish between using AI as a supportive tool and over-relying on it at the expense of their own critical thinking skills.",
      ar: "أداة نقاش سريعة للصف أو العائلة."
    },
    link: "https://dayofai.org/units/the-cognitive-card-game",
    tags: ["activity","fast_classroom_activity","ethics"]
  },
  {
    id: "truth-tricks-day-of-ai-md",
    name: { en: "Classroom module on misinformation, persuasion, and how to check claims about AI", ar: "وحدة صفية حول المعلومات المضللة والإقناع والتحقق من الادعاءات حول الذكاء الاصطناعي" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Provides specific strategies to counter AI hallucinations and biases.",
      ar: "تمارين على التفكير النقدي ومصادر الأخبار والتحقق من الحقائق."
    },
    link: "https://dayofai.org/units/truth-tricks-and-ai-learning-to-verify-information",
    tags: ["lesson_plan","activity","media_literacy"]
  },
  {
    id: "using-ai-for-creativity",
    name: { en: "Guided prompts for creative projects that keep authorship and ethics in view", ar: "مسارات إبداعية باستخدام الذكاء الاصطناعي مع الحفاظ على الألفة والأخلاقيات" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Introduces younger students to the concept of AI-assisted creativity, comparing how humans and AI think differently when generating ideas.",
      ar: "تمارين تركز على المؤلف البشري والإفصاح عن استخدام الذكاء الاصطناعي."
    },
    link: "https://dayofai.org/units/using-ai-for-creativity",
    tags: ["lesson_plan","activity","storytelling"]
  },
  {
    id: "what-is-artificial-intelligence",
    name: { en: "Plain-language explainer: definitions, limits, and everyday examples", ar: "شرح مبسط: تعريفات الذكاء الاصطناعي، حدوده، وأمثلة من اليومية" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Foundational unit that defines AI and algorithms. Crucial for Ethika as it introduces how human choices in data and algorithm design lead to optimization and bias. Distinguishes between human intelligence and machine learning.",
      ar: "نقطة انطلاق للآباء قبل الحديث مع الأطفال."
    },
    link: "https://dayofai.org/units/what-is-artificial-intelligence",
    tags: ["curriculum","lesson_plan","foundational","activity"]
  },
  {
    id: "women-trailblazers-ai",
    name: { en: "Profiles of women leaders in AI and CS for classroom or home inspiration", ar: "نماذج من قيادات نسائية في الذكاء الاصطناعي وعلوم الحاسب كمصدر إلهام" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Critical for addressing the gender gap and bias in AI by highlighting the essential contributions of women to the field, fostering a more inclusive perspective.",
      ar: "سير قصيرة تناسب الفصل أو القراءة العائلية."
    },
    link: "https://dayofai.org/units/women-trailblazers-in-ai-and-computer-science",
    tags: ["mini-unit","history","biography"]
  },
  {
    id: "work-in-the-age-of-ai",
    name: { en: "Overview of how automation and AI change skills, tasks, and career paths", ar: "كيف يغيّر الأتمتة والذكاء الاصطناعي المهارات والمهام ومسارات العمل" },
    category: "learning",
    ageMin: 8,
    ageMax: 16,
    free: true,
    ksaAvailable: true,
    arabicSupport: true,
    privacyLevel: "medium",
    privacyNote: {
      en: "Review the site’s terms with your child. Educational providers may collect usage data.",
      ar: "راجعوا شروط الموقع مع طفلكم؛ قد تجمع الجهات التعليمية بيانات الاستخدام."
    },
    description: {
      en: "Analyzes how AI transforms tasks and careers, with a specific focus on ethical trade-offs and algorithmic bias in professional fields, emphasizing uniquely human skills.",
      ar: "يساعد المراهقين على ربط التعلم بالفرص المستقبلية."
    },
    link: "https://dayofai.org/units/work-in-the-age-of-ai",
    tags: ["lesson_plan","activity","ethics"]
  },
];

export const KNOWLEDGE_HUB_EXTRA_ACTIVITIES = [
  {
    id: "common-sense-1st-grade-family-activity-digital-citizensh",
    title: { en: "Kindness, respect & safety in online spaces — Grade 1", ar: "اللطف والاحترام والسلامة في العالم الرقمي — الصف الأول" },
    ageBand: "6-9",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: Kindness, respect & safety in online spaces — Grade 1", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-1st-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1VMGK_30rrMq4tD-VI6j5Z0RoPAolT_lydAaP03VoEHM/"
  },
  {
    id: "common-sense-2nd-grade-family-activity-digital-citizensh",
    title: { en: "Kindness, respect & safety in online spaces — Grade 2", ar: "اللطف والاحترام والسلامة في العالم الرقمي — الصف الثاني" },
    ageBand: "6-9",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: Kindness, respect & safety in online spaces — Grade 2", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-2nd-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1tsYWY76Y9BJpl_mHcxb0-BiLIHL2PrGBt3GqeeBNAD8/"
  },
  {
    id: "common-sense-3-4-grade-family-activity-digital-footprint",
    title: { en: "What stays online: footprints, identity & reputation — Grades 3–4", ar: "ما يبقى على الإنترنت: البصمة والهوية والسمعة — الصفوف 3–4" },
    ageBand: "6-9",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: What stays online: footprints, identity & reputation — Grades 3–4", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-3-4-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1jqE5CLfzAjXdLY-6c26Ri15XNeidRAFU1jt47TmJ6GQ/"
  },
  {
    id: "common-sense-3-5-family-activity-cards",
    title: { en: "Take-home prompts & activities for family conversations — Grades 3–5", ar: "أفكار وأنشطة للنقاش العائلي في المنزل — الصفوف 3–5" },
    ageBand: "6-9",
    durationMinutes: 25,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Adapts digital citizenship concepts for older elementary students using more complex game formats", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Adapts digital citizenship concepts for older elementary students using more complex game formats. It introduces critical topics like AI-generated content, online boundaries, consent, and media balance through interactive family play.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "hands-on",
    tags: ["imported","common-sense-3-5-fam"],
    resourceUrl: "https://docs.google.com/document/d/1jmM7vNKNRnGu79SsCLJ9N-pHfr5bbhlbJupi_m9acJA/"
  },
  {
    id: "common-sense-3-5-family-activity-media-balance",
    title: { en: "Healthy screen time, sleep & emotional balance — Grades 3–5", ar: "توازن الشاشات والنوم والرفاهية العاطفية — الصفوف 3–5" },
    ageBand: "6-9",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "This activity for grades 3-5 focuses on performing a 'media balance checkup' within the family", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "This activity for grades 3-5 focuses on performing a 'media balance checkup' within the family. It encourages critical thinking about how digital devices affect sleep, meals, and family interactions, and helps families decide on healthy changes together.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-3-5-fam"],
    resourceUrl: "https://docs.google.com/presentation/d/159Ly4QWfekuO5ogeLVouMWIo5oxmxB2QCP9X00rjkRE/"
  },
  {
    id: "common-sense-3-5-grade-family-activity-cyberbullying-dig",
    title: { en: "When online conflict hurts: response & support — Grades 3–5", ar: "عندما يؤذي التنمر عبر الشبكة: الاستجابة والدعم — الصفوف 3–5" },
    ageBand: "6-9",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: When online conflict hurts: response & support — Grades 3–5", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-3-5-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1QXn58bg3G4ptPeEpG2nuzF7CmOgXYq8HBbfUWGxRv98/"
  },
  {
    id: "common-sense-3-5-grade-family-activity-news-media-litera",
    title: { en: "Telling reliable news from rumors & manipulated media — Grades 3–5", ar: "تمييز الأخبار الموثوقة عن الشائعات والمحتوى المُلاعب — الصفوف 3–5" },
    ageBand: "6-9",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: Telling reliable news from rumors & manipulated media — Grades 3–5", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-3-5-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1yldihO3NSv3h1FGoQ0Sjrh1RVlKiY7cSjWnHOnR0ye4/"
  },
  {
    id: "common-sense-3-5-grade-family-activity-relationships-com",
    title: { en: "Texts, friendships & respectful communication — Grades 3–5", ar: "الرسائل والصداقة والتواصل باحترام — الصفوف 3–5" },
    ageBand: "6-9",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: Texts, friendships & respectful communication — Grades 3–5", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-3-5-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1JCtmMfyBZI-erk0okvW7qNLoxRPzCN6SgqI0dhAEIXk/"
  },
  {
    id: "common-sense-3rd-grade-family-activity-privacy-security",
    title: { en: "Passwords, accounts & protecting personal information — Grade 3", ar: "كلمات المرور والحسابات وحماية المعلومات الشخصية — الصف الثالث" },
    ageBand: "6-9",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: Passwords, accounts & protecting personal information — Grade 3", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-3rd-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1l2V8WgjE_6g3jtjfq9oYDsZi7OPT5Gs8bvBTfe3kSD0/"
  },
  {
    id: "common-sense-4th-grade-family-activity-privacy-safety",
    title: { en: "Sharing less, spotting risks & asking for help — Grade 4", ar: "مشاركة أقل واكتشاف المخاطر وطلب المساعدة — الصف الرابع" },
    ageBand: "6-9",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: Sharing less, spotting risks & asking for help — Grade 4", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-4th-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1bmLPp3Fi7GVDbE5Fjv7hVjGMusNfSCiIWjfFuyEcXzA/"
  },
  {
    id: "common-sense-5th-grade-family-activity-digital-footprint",
    title: { en: "What stays online: footprints, identity & reputation — Grade 5", ar: "ما يبقى على الإنترنت: البصمة والهوية والسمعة — الصف الخامس" },
    ageBand: "6-9",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: What stays online: footprints, identity & reputation — Grade 5", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-5th-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1Mi7KN3WDV_6snpzfHeoVtczIqvKU_-cT4vCbrXWRvaA/"
  },
  {
    id: "common-sense-5th-grade-family-activity-privacy-safety",
    title: { en: "Sharing less, spotting risks & asking for help — Grade 5", ar: "مشاركة أقل واكتشاف المخاطر وطلب المساعدة — الصف الخامس" },
    ageBand: "6-9",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: Sharing less, spotting risks & asking for help — Grade 5", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-5th-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1J05BBp_lgFf2I883yFv1WXziAqI7PDsCcoB06fa2L3g/"
  },
  {
    id: "common-sense-6-8-family-activity-cards",
    title: { en: "Take-home prompts & activities for family conversations — Grades 6–8", ar: "أفكار وأنشطة للنقاش العائلي في المنزل — الصفوف 6–8" },
    ageBand: "10-13",
    durationMinutes: 25,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Adapts digital citizenship concepts for middle school students through interactive verbal games", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Adapts digital citizenship concepts for middle school students through interactive verbal games. It covers advanced topics such as AI chatbots, online reputation, mental health, and media literacy, encouraging deep discussion between adolescents and adults.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "hands-on",
    tags: ["imported","common-sense-6-8-fam"],
    resourceUrl: "https://docs.google.com/document/d/1ish9uIercKZJOTsi2vVtKOClhwAy9GMTEDq-as_kmJk/"
  },
  {
    id: "common-sense-6-8-grade-family-activity-cyberbullying-dig",
    title: { en: "When online conflict hurts: response & support — Grades 6–8", ar: "عندما يؤذي التنمر عبر الشبكة: الاستجابة والدعم — الصفوف 6–8" },
    ageBand: "10-13",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: When online conflict hurts: response & support — Grades 6–8", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-6-8-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/14-6deXF8qN8e_ev2SORPDK4FXcMdno5t3cEH0l6cmzU/"
  },
  {
    id: "common-sense-6-8-grade-family-activity-digital-footprint",
    title: { en: "What stays online: footprints, identity & reputation — Grades 6–8", ar: "ما يبقى على الإنترنت: البصمة والهوية والسمعة — الصفوف 6–8" },
    ageBand: "10-13",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: What stays online: footprints, identity & reputation — Grades 6–8", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-6-8-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1sj-HlUS7ybkgCUUjW1T1b01qlQYk82Kk8YnECuP-eOc/"
  },
  {
    id: "common-sense-6-8-grade-family-activity-media-balance",
    title: { en: "Healthy screen time, sleep & emotional balance — Grades 6–8", ar: "توازن الشاشات والنوم والرفاهية العاطفية — الصفوف 6–8" },
    ageBand: "10-13",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: Healthy screen time, sleep & emotional balance — Grades 6–8", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-6-8-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1moJRD4r9umukn7MwZ847tTMRRYYt7Uu2ym1lAw1zHoI/"
  },
  {
    id: "common-sense-6-8-grade-family-activity-news-media-litera",
    title: { en: "Telling reliable news from rumors & manipulated media — Grades 6–8", ar: "تمييز الأخبار الموثوقة عن الشائعات والمحتوى المُلاعب — الصفوف 6–8" },
    ageBand: "10-13",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: Telling reliable news from rumors & manipulated media — Grades 6–8", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-6-8-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1vj_H9D7LxFWMLbI3iI3q58ImBCyudhmbQrO5xBURiH8/"
  },
  {
    id: "common-sense-6-8-grade-family-activity-privacy-security",
    title: { en: "Passwords, accounts & protecting personal information — Grades 6–8", ar: "كلمات المرور والحسابات وحماية المعلومات الشخصية — الصفوف 6–8" },
    ageBand: "10-13",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: Passwords, accounts & protecting personal information — Grades 6–8", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-6-8-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1IbLnMNfX4tPHQq_14D6I2tdE9tI5apVqtZSRL4rnhGc/"
  },
  {
    id: "common-sense-6-8-grade-family-activity-relationships-com",
    title: { en: "Texts, friendships & respectful communication — Grades 6–8", ar: "الرسائل والصداقة والتواصل باحترام — الصفوف 6–8" },
    ageBand: "10-13",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: Texts, friendships & respectful communication — Grades 6–8", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-6-8-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1pSvIk4Bn0Dz-q2q8PuRc9cGFAsuLh8K-AYyxf-l2KEI/"
  },
  {
    id: "common-sense-7th-grade-family-activity-news-media-litera",
    title: { en: "Telling reliable news from rumors & manipulated media — Grade 7", ar: "تمييز الأخبار الموثوقة عن الشائعات والمحتوى المُلاعب — الصف السابع" },
    ageBand: "10-13",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: Telling reliable news from rumors & manipulated media — Grade 7", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-7th-gra"],
    resourceUrl: "https://docs.google.com/presentation/d/1WVWL6fEuMM6VyyNMmFqy-UjsoPnVeshwG0wy1CZ-GRk/"
  },
  {
    id: "common-sense-9-12-family-activity-cards",
    title: { en: "Take-home prompts & activities for family conversations — Grades 9–12", ar: "أفكار وأنشطة للنقاش العائلي في المنزل — الصفوف 9–12" },
    ageBand: "14-16",
    durationMinutes: 25,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Adapts digital citizenship concepts for high school students through verbal games like 'Would You Rather' and 'Never Have I Ever'", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Adapts digital citizenship concepts for high school students through verbal games like 'Would You Rather' and 'Never Have I Ever'. It addresses mature topics such as parasocial relationships, digital disinhibition, AI environmental impacts, and body image pressures to foster deep family dialogue.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "hands-on",
    tags: ["imported","common-sense-9-12-fa"],
    resourceUrl: "https://docs.google.com/document/d/15ZZsOvofhyr1kZMUXP5uozn-fC_Gs-ZOlPDoMDMMdEY/"
  },
  {
    id: "common-sense-k-2-family-activity-cards",
    title: { en: "Take-home prompts & activities for family conversations — K–2", ar: "أفكار وأنشطة للنقاش العائلي في المنزل — التمهيدي–2" },
    ageBand: "3-5",
    durationMinutes: 25,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: Take-home prompts & activities for family conversations — K–2", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "hands-on",
    tags: ["imported","common-sense-k-2-fam"],
    resourceUrl: "https://docs.google.com/document/d/1-jDKXgF0kuzEWIOG3j-9vwSw9qJEihtAnIskOi7Y_JU/"
  },
  {
    id: "common-sense-k-family-activity-media-balance",
    title: { en: "Healthy screen time, sleep & emotional balance — Kindergarten", ar: "توازن الشاشات والنوم والرفاهية العاطفية — رياض الأطفال" },
    ageBand: "3-5",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Use the linked Common Sense resource to guide a short family conversation about: Healthy screen time, sleep & emotional balance — Kindergarten", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Watch how your child connects the examples in the slides to their own online experiences.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","common-sense-k-famil"],
    resourceUrl: "https://docs.google.com/presentation/d/17Tq9wgw2F9sMkE2Z2a2zkriLK0zp1qDsSkv5YTB7Ldg/"
  },
  {
    id: "family-guide-video1-what-is-ai",
    title: { en: "Short parent video: what AI is (and isn’t) in everyday language", ar: "فيديو قصير للوالدين: ما الذكاء الاصطناعي (وما ليس كذلك) بلغة بسيطة" },
    ageBand: "6-9",
    durationMinutes: 20,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "A foundational tool for home-school connection", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "A foundational tool for home-school connection. It provides families with a structured way to start conversations about what AI is and how it works using interactive activities, making technical concepts accessible and relatable.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","family-guide-video1-"],
    resourceUrl: "https://drive.google.com/drive/folders/1dUdFo-mQpLqVYCUdtKt-1zvCJWl10iDk"
  },
  {
    id: "family-guide-video2-talking-to-kids",
    title: { en: "Short parent video: how to talk with kids about AI calmly", ar: "فيديو قصير للوالدين: كيف تتحدث مع أطفالك عن الذكاء الاصطناعي بهدوء" },
    ageBand: "6-9",
    durationMinutes: 20,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Directly supports Ethika's mission by moving beyond technical basics into the moral dimension of AI", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Directly supports Ethika's mission by moving beyond technical basics into the moral dimension of AI. It empowers families to discuss complex topics like privacy and fairness in a way that is age-appropriate and meaningful.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","family-guide-video2-"],
    resourceUrl: "https://drive.google.com/drive/folders/1o-yjVkh69aY_F2ZPqgNBAxONNOzQRIvk"
  },
  {
    id: "family-guide-video3-ai-for-schoolwork",
    title: { en: "Short parent video: homework, honesty & using AI for schoolwork", ar: "فيديو قصير للوالدين: الواجبات والصدق واستخدام الذكاء الاصطناعي في الدراسة" },
    ageBand: "6-9",
    durationMinutes: 20,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Addresses the immediate practical challenge of AI in education", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Addresses the immediate practical challenge of AI in education. It provides a framework for families to ensure AI is used as a supportive learning tool rather than a shortcut, fostering academic integrity and thoughtful engagement.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","family-guide-video3-"],
    resourceUrl: "https://drive.google.com/drive/folders/1ovWBKTxDKVDRbMOO7FvtLQlsmFgJ0wMJ"
  },
  {
    id: "kids-and-tech-discussion-guide-families",
    title: { en: "Companion guide: discussing each Kids & Tech episode as a family", ar: "دليل مرافق: مناقشة كل حلقة من «الأطفال والتقنية» معاً كعائلة" },
    ageBand: "6-9",
    durationMinutes: 25,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Synthesizes the core messages of the video series into a practical conversation toolkit", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Synthesizes the core messages of the video series into a practical conversation toolkit. It moves from passive viewing to active family engagement, encouraging parents to build trust and shared understanding with their children regarding technology use.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","kids-and-tech-discus"],
    resourceUrl: "https://www.commonsense.org/system/files?file=pdf/2023-09/kids-and-tech-video-series.pdf"
  },
  {
    id: "kids-and-tech-screen-time-guide",
    title: { en: "Talking points on screen time, sleep & family agreements", ar: "نقاط للحديث عن وقت الشاشة والنوم والاتفاقيات العائلية" },
    ageBand: "6-9",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Provides a balanced framework for managing screen time across different age groups", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Provides a balanced framework for managing screen time across different age groups. It emphasizes the quality of content and the nature of the engagement (passive, interactive, creative) over strict hourly limits, fostering a healthy and conscious relationship with technology.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","kids-and-tech-screen"],
    resourceUrl: "https://www.youtube.com/watch?v=1WhzaO0DVJM"
  },
  {
    id: "kids-and-tech-when-to-get-a-phone",
    title: { en: "Readiness checklist: when a first phone makes sense for your child", ar: "قائمة الجاهزية: متى يكون الهاتف الأول مناسباً لطفلك" },
    ageBand: "6-9",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Provides a practical framework for families to assess when a child is developmentally and emotionally ready for the responsibility of a personal device", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Provides a practical framework for families to assess when a child is developmentally and emotionally ready for the responsibility of a personal device. It emphasizes value-based decision-making and proactive safety measures, aligning with responsible digital citizenship.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","kids-and-tech-when-t"],
    resourceUrl: "https://www.youtube.com/watch?v=F_gJpV8Co-s"
  },
  {
    id: "parenting-in-the-age-of-ai-playlist",
    title: { en: "Curated talks for parents on raising kids alongside AI tools", ar: "محادثات مختارة للوالدين عن تربية الأطفال مع أدوات الذكاء الاصطناعي" },
    ageBand: "6-9",
    durationMinutes: 35,
    toolsNeeded: { en: "Internet access and the linked resource (slides, PDF, or video).", ar: "اتصال بالإنترنت والمورد المرتبط (عرض أو PDF أو فيديو)." },
    openingPrompt: { en: "Provides practical, high-level advice for parents navigating the challenges of AI", ar: "استخدموا المورد المرتبط كدليل لجلسة عائلية قصيرة؛ شاركوا أمثلة من أسبوعكم وتناوبوا على الاستماع دون مقاطعة." },
    whatToNotice: { en: "Provides practical, high-level advice for parents navigating the challenges of AI. It focuses on how AI changes child development, safety, and the parent-child relationship, offering actionable tips for managing technology at home.", ar: "لاحظوا كيف يفكر طفلكم في الخيارات الرقمية وهل يربط القواعد بأمثلة من حياته." },
    followUp: { en: "Agree on one small family habit to try this week (e.g., checking a headline together or a screen-off time).", ar: "اتفقوا على عادة عائلية صغيرة لهذا الأسبوع (مثل التحقق من عنوان معاً أو وقت لإطفاء الشاشات)." },
    category: "discussion",
    tags: ["imported","parenting-in-the-age"],
    resourceUrl: "https://www.youtube.com/playlist?list=PL8TjVyuBdsClLe-x6eHRcn7l7bN5XgrlG"
  },
];

export const KNOWLEDGE_HUB_EXTRA_ORGANIZATIONS = [
  {
    id: "children-and-incompetents-data-protection-policy",
    name: { en: "Children's Personal Data Protection Policy", ar: "سياسة حماية بيانات الأطفال ومن في حكمهم" },
    focusArea: "ai-ethics",
    focus: { en: "Specifically addresses protections for children's personal data and guardian responsibilities.", ar: "توضح التزامات ولي الأمر والجهات تجاه بيانات القُصّر." },
    link: "https://sdaia.gov.sa/ar/SDAIA/about/Documents/Children%20and%20Incompetents%E2%80%99%20Data%20Protection%20Policy.pdf",
    hasLink: true,
    region: "saudi"
  },
  {
    id: "digital-government-authority-ai-ethics-principles-page",
    name: { en: "Digital Government Authority · AI Ethics Principles", ar: "هيئة الحكومة الرقمية — مبادئ أخلاقيات الذكاء الاصطناعي" },
    focusArea: "ai-ethics",
    focus: { en: "Explains ethical AI principles applied in Saudi public sector, reinforcing trust, accountability, and transparency.", ar: "تشرح مبادئ الاستخدام الأخلاقي للذكاء الاصطناعي في القطاع العام وبناء الثقة." },
    link: "https://dga.gov.sa/en/AI-Ethics-Principles",
    hasLink: true,
    region: "saudi"
  },
  {
    id: "personal-data-protection-law-pdpl-english-version",
    name: { en: "Personal Data Protection Law (PDPL) · English", ar: "نظام حماية البيانات الشخصية (النسخة الإنجليزية)" },
    focusArea: "ai-ethics",
    focus: { en: "Core Saudi privacy law governing personal data processing, consent, and protection of children's data.", ar: "الإطار القانوني الأساسي في المملكة لمعالجة البيانات الشخصية والموافقة وحماية بيانات الأطفال." },
    link: "https://sdaia.gov.sa/en/SDAIA/about/Documents/Personal%20Data%20English%20V2-23April2023-%20Reviewed-.pdf",
    hasLink: true,
    region: "saudi"
  },
  {
    id: "sdaia-genai-instructions",
    name: { en: "What families and schools should know: safe, responsible use of tools like ChatGPT (plain-language national guide)", ar: "ما ينبغي أن تعرفه العائلات والمدارس: استخدام آمن ومسؤول لأدوات مثل ChatGPT (دليل وطني مبسّط)" },
    focusArea: "ai-ethics",
    focus: { en: "Official public guidance explaining safe and responsible use of generative AI.", ar: "إرشادات عامة رسمية حول الاستخدام الآمن والمسؤول للذكاء الاصطناعي التوليدي." },
    link: "https://sdaia.gov.sa/en/SDAIA/about/Files/GenerativeAIPublicEN.pdf",
    hasLink: true,
    region: "saudi"
  },
  {
    id: "sdaia-ai-ethics-principles",
    name: { en: "SDAIA · AI Ethics Principles", ar: "سدايا — مبادئ أخلاقيات الذكاء الاصطناعي" },
    focusArea: "ai-ethics",
    focus: { en: "Foundational national AI ethics principles that define fairness, accountability, transparency, privacy, and human oversight in AI systems.", ar: "مبادئ وطنية أساسية حول العدالة والمساءلة والشفافية والخصوصية والإشراف البشري على الأنظمة الذكية." },
    link: "https://sdaia.gov.sa/en/SDAIA/about/Documents/ai-principles.pdf",
    hasLink: true,
    region: "saudi"
  },
  {
    id: "sdaia-generative-ai-guidelines-for-government",
    name: { en: "How public institutions should use generative AI: risks, privacy, and keeping humans in the loop (national guide)", ar: "كيف تستخدم المؤسسات العامة الذكاء الاصطناعي التوليدي: المخاطر والخصوصية وبقاء الإنسان في الحلقة" },
    focusArea: "ai-ethics",
    focus: { en: "Explains risks of generative AI including misinformation, hallucinations, privacy risks, and the importance of human review.", ar: "يوضح مخاطر التضليل والهلوسة وخصوصية البيانات وأهمية المراجعة البشرية في القطاع الحكومي." },
    link: "https://sdaia.gov.sa/en/SDAIA/about/Files/GenAIGuidelinesForGovernmentENCompressed.pdf",
    hasLink: true,
    region: "saudi"
  },
  {
    id: "sdaia-national-strategy-for-data-ai-nsdai",
    name: { en: "National Strategy for Data & AI", ar: "الاستراتيجية الوطنية للبيانات والذكاء الاصطناعي" },
    focusArea: "ai-ethics",
    focus: { en: "Provides national context for AI adoption in Saudi Arabia and alignment with Vision 2030, useful for explaining why AI literacy is important for families.", ar: "سياق وطني لاعتماد الذكاء الاصطناعي في المملكة وارتباطه برؤية 2030." },
    link: "https://sdaia.gov.sa/en/SDAIA/SdaiaStrategies/Pages/NationalStrategyForDataAndAI.aspx",
    hasLink: true,
    region: "saudi"
  },
  {
    id: "src-1cyjpzi",
    name: { en: "المبادئ الأخلاقية للذكاء الاصطناعي", ar: "المبادئ الأخلاقية للذكاء الاصطناعي" },
    focusArea: "ai-ethics",
    focus: { en: "Official Saudi government reference for parents and educators (Arabic document at the link).", ar: "يوضح المبادئ الوطنية للاستخدام المسؤول للذكاء الاصطناعي." },
    link: "https://sdaia.gov.sa/ar/SDAIA/about/Documents/ai-principles-ar.pdf",
    hasLink: true,
    region: "saudi",
    locales: ["ar"]
  },
  {
    id: "src-12ueoeq",
    name: { en: "سياسة حماية البيانات الشخصية للأطفال ومن في حكمهم", ar: "سياسة حماية البيانات الشخصية للأطفال ومن في حكمهم" },
    focusArea: "ai-ethics",
    focus: { en: "Official Saudi government reference for parents and educators (Arabic document at the link).", ar: "مرجع رسمي يوضح مسؤوليات ولي الأمر في حماية بيانات الأطفال الرقمية." },
    link: "https://sdaia.gov.sa/ar/SDAIA/about/Documents/Children%20and%20Incompetents%E2%80%99%20Data%20Protection%20Policy.pdf",
    hasLink: true,
    region: "saudi",
    locales: ["ar"]
  },
  {
    id: "src-wndt2v",
    name: { en: "التوعية بالأمن السيبراني للأطفال", ar: "التوعية بالأمن السيبراني للأطفال" },
    focusArea: "ai-ethics",
    focus: { en: "Official Saudi government reference for parents and educators (Arabic document at the link).", ar: "مواد توعوية رسمية تساعد أولياء الأمور على حماية أطفالهم من المخاطر الرقمية." },
    link: "https://nca.gov.sa/ar/awareness/",
    hasLink: true,
    region: "saudi",
    locales: ["ar"]
  },
  {
    id: "src-1wm7vab",
    name: { en: "إرشادات الذكاء الاصطناعي التوليدي", ar: "إرشادات الذكاء الاصطناعي التوليدي" },
    focusArea: "ai-ethics",
    focus: { en: "Official Saudi government reference for parents and educators (Arabic document at the link).", ar: "مرجع وطني يشرح مخاطر وفوائد الذكاء الاصطناعي التوليدي وكيفية استخدامه بشكل مسؤول." },
    link: "https://sdaia.gov.sa/ar/SDAIA/about/Files/GenerativeAIPublicAR.pdf",
    hasLink: true,
    region: "saudi",
    locales: ["ar"]
  },
  {
    id: "src-gasns5",
    name: { en: "نظام حماية البيانات الشخصية", ar: "نظام حماية البيانات الشخصية" },
    focusArea: "ai-ethics",
    focus: { en: "Official Saudi government reference for parents and educators (Arabic document at the link).", ar: "الإطار القانوني الرسمي لحماية البيانات الشخصية داخل المملكة، بما يشمل بيانات القُصّر." },
    link: "https://sdaia.gov.sa/ar/SDAIA/about/Documents/Personal%20Data.pdf",
    hasLink: true,
    region: "saudi",
    locales: ["ar"]
  },
  {
    id: "src-1au5r7w",
    name: { en: "التحول الرقمي في التعليم", ar: "التحول الرقمي في التعليم" },
    focusArea: "ai-ethics",
    focus: { en: "Official Saudi government reference for parents and educators (Arabic document at the link).", ar: "يوضح توجه وزارة التعليم في دمج التقنية والذكاء الاصطناعي في العملية التعليمية." },
    link: "https://www.moe.gov.sa/ar/aboutus/digitaltransformation",
    hasLink: true,
    region: "saudi",
    locales: ["ar"]
  },
  {
    id: "src-wn6yua",
    name: { en: "الإطار الوطني لسلامة الطفل على الإنترنت", ar: "الإطار الوطني لسلامة الطفل على الإنترنت" },
    focusArea: "ai-ethics",
    focus: { en: "Official Saudi government reference for parents and educators (Arabic document at the link).", ar: "يوضح السياسات الوطنية لحماية الأطفال من المخاطر الرقمية." },
    link: "https://www.hrsd.gov.sa/ar/media-center/news/121120237",
    hasLink: true,
    region: "saudi",
    locales: ["ar"]
  },
];
